2023-03-14 13:56:02,125 - WARNING: Failed to create connection pool for new host 172.20.0.3:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3175, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool
  File "cassandra/pool.py", line 402, in cassandra.pool.HostConnection.__init__
  File "cassandra/cluster.py", line 1620, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 831, in cassandra.connection.Connection.factory
  File "/Users/wendyarevalo/Library/CloudStorage/OneDrive-Personal/Documents OneDrive/assignment-2-100517312/venv/lib/python3.9/site-packages/cassandra/io/asyncorereactor.py", line 344, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 898, in cassandra.connection.Connection._connect_socket
OSError: [Errno None] Tried connecting to [('172.20.0.3', 9042)]. Last error: timed out
2023-03-14 13:56:02,135 - WARNING: Host 172.20.0.3:9042 has been marked down
2023-03-14 13:56:08,287 - WARNING: Error attempting to reconnect to 172.20.0.3:9042, scheduling retry in 2.02 seconds: [Errno None] Tried connecting to [('172.20.0.3', 9042)]. Last error: timed out
2023-03-14 13:56:15,361 - WARNING: Error attempting to reconnect to 172.20.0.3:9042, scheduling retry in 3.48 seconds: [Errno None] Tried connecting to [('172.20.0.3', 9042)]. Last error: timed out
2023-03-14 13:56:23,511 - INFO: tenant1 Added tenant1-1433116799.json, with a size of 0.0024547576904296875 MB
2023-03-14 13:56:23,529 - INFO: tenant1 Started ingestion of json file at 2023-03-14 13:56:23.529839
2023-03-14 13:56:23,641 - INFO: tenant1 Finished ingestion at 2023-03-14 13:56:23.639418 a total of 0.0024547576904296875
2023-03-14 13:56:23,890 - WARNING: Error attempting to reconnect to 172.20.0.3:9042, scheduling retry in 6.8 seconds: [Errno None] Tried connecting to [('172.20.0.3', 9042)]. Last error: timed out
2023-03-14 13:56:35,734 - WARNING: Error attempting to reconnect to 172.20.0.3:9042, scheduling retry in 15.68 seconds: [Errno None] Tried connecting to [('172.20.0.3', 9042)]. Last error: timed out
2023-03-14 13:56:56,443 - WARNING: Error attempting to reconnect to 172.20.0.3:9042, scheduling retry in 32.0 seconds: [Errno None] Tried connecting to [('172.20.0.3', 9042)]. Last error: timed out
2023-03-14 13:57:05,614 - INFO: tenant2 Added tenant2-1433116799.csv, with a size of 0.0033969879150390625 MB
2023-03-14 13:57:05,628 - INFO: tenant2 Started ingestion of csv file at 2023-03-14 13:57:05.628003
2023-03-14 13:57:05,744 - INFO: tenant2 Finished ingestion at 2023-03-14 13:57:05.743194 a total of 0.0033969879150390625
2023-03-14 13:57:24,067 - INFO: tenant1 Added tenant1-sd.txt, with a size of 0.0 MB
2023-03-14 13:57:24,075 - ERROR: tenant1 The extension '.txt' is not supported
2023-03-14 13:57:24,075 - ERROR: tenant1 An error occurred in the validation process
2023-03-14 13:58:16,201 - INFO: tenant1 Added tenant1-1433110000_1433100000.json, with a size of 35.186673164367676 MB
2023-03-14 13:58:16,207 - ERROR: tenant1 35.186673164367676 MB exceeds the limit of file size of 10 MB
2023-03-14 13:58:16,208 - ERROR: tenant1 An error occurred in the validation process
2023-03-14 13:59:04,458 - INFO: tenant1 Added tenant1-1433116799.json, with a size of 0.0024547576904296875 MB
2023-03-14 13:59:04,475 - ERROR: tenant1 The limit of files per day (5) has been reached. Current files is 35
2023-03-14 13:59:04,475 - ERROR: tenant1 An error occurred in the validation process
2023-03-14 13:59:29,432 - INFO: tenant1 Added tenant1-1433116799.json, with a size of 0.0024547576904296875 MB
2023-03-14 13:59:29,455 - ERROR: tenant1 The limit per day (5 MB) has been reached. Current size is 19.326091766357422
2023-03-14 13:59:29,455 - ERROR: tenant1 An error occurred in the validation process
